version: "3.7"


services:
  nginx:
    container_name: nginx
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/www/public
    extra_hosts:
      - "host.docker.internal:${DOCKER_IP}"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
